name: Build goodsbutton

on: [push]  # 触发条件，这里是代码被推送到仓库时

jobs:
  build-and-release:
    runs-on: ubuntu-latest  # 运行环境，这里是最新的Ubuntu系统
    permissions:
      contents: write
    steps:
    - name: Checkout code  # 检出代码
      uses: actions/checkout@v2

    - name: Setup PlatformIO  # 设置PlatformIO
      uses: n-vr/setup-platformio-action@v1

    - name: Build   # 构建项目
      run: |
        cd ./goodsbutton
        pio run
    - name: Create Release and Upload Bin  # 创建Release并上传.bin文件
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')  # 如果是标签推送，则执行Release操作
      with:
        files: goodsbutton/.pio/build/goodsbutton/goodsbutton_4MB.bin  # 上传的文件路径
        body: |
          ### mini开关固件
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用GitHub提供的token