name: 功率计代码CI/CD

on: [push]  # 触发条件，这里是代码被推送到仓库时

jobs:
  build-and-release:
    runs-on: ubuntu-latest  # 运行环境，这里是最新的Ubuntu系统
    permissions:
      contents: write
    steps:
    - name: Checkout code  # 检出代码
      uses: actions/checkout@v2

    - name: Setup PlatformIO  # 设置PlatformIO
      uses: n-vr/setup-platformio-action@v1

    - name: Build   # 构建项目
      run: |
        cd ./Wireless_power_meter
        pio run
        ls -R Wireless_power_meter/.pio/build/Wireless_power_meter
        ls -R Wireless_power_meter/.pio/build/Wireless_power_meter_pro

    - name: Create Release and Upload Bin  # 创建Release并上传.bin文件
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')  # 如果是标签推送，则执行Release操作
      with:
        files: |
          ${{ github.workspace }}/Wireless_power_meter/.pio/build/Wireless_power_meter/Wireless_power_meter_4MB.bin
          ${{ github.workspace }}/Wireless_power_meter/.pio/build/Wireless_power_meter_pro/Wireless_power_meter_pro_4MB.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用GitHub提供的token